spring.application.name=bug-triage-backend

# Ket noi db
spring.datasource.url=jdbc:postgresql://localhost:5432/bug_triage_db
spring.datasource.username=postgres
spring.datasource.password=asd123hien

# Cau hinh Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Config
bugtriage.app.jwtSecret=BugTriageSecretKeyForJWTAuth2024DoNotShare12345
bugtriage.app.jwtExpirationMs=86400000